Update study.csv
adknowledgeportal/data-models pull request #44
Opened 2023-12-04 16:23 UTC by ameliakallaher

I added a new study, MARS WISCONSIN, to the CSV file.

2023-12-04 17:12 UTC, avanlinden requested changes
#

2023-12-04 17:12 UTC, avanlinden commented on modules/ADKP/study.csv
Make sure to add the new study abbreviation in the comma-separated list in the Valid Values column for the `study` attribute (line 2) in the file. I'm planning to write something that automatically does that because I've already forgotten it a few times myself, but for now we gotta do it manually!

2024-01-19 17:27 UTC, ameliakallaher commented on modules/ADKP/study.csv
I corrected this with "Update study.csv #44," where I added the study abbreviation for MARS WISCONSIN study in line 2.

2024-01-22 17:20 UTC, avanlinden commented on modules/ADKP/study.csv
cool, I'll close this PR then!

2024-01-22 17:20 UTC, closed without merging